---
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=toor
      - TZ=Europe/Vienna
      - MYSQL_DATABASE=ddd-demo
      - MYSQL_USER=ddd-demo
      - MYSQL_PASSWORD=demo1
    volumes:
      - ddd-demo-data:/config
    ports:
      - 3306:3306
    restart: unless-stopped
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: toor
#    volumes:
#      - "ddd-demo-mongodb-data:/etc/mongo"
#    ports:
#      - "27017:27017"
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
#      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/
volumes:
  ddd-demo-data:
#  ddd-demo-mongodb-data:
